#zuul gateway properties
#core1 -> discover service instances using consul using serviceId core-app-1
#http://localhost:7071/gateway/products
#core2 -> use provided url to route to core-app-2
#http://localhost:7071/gateway/prices

core-app-2-base-url: http://localhost:9095/app2

zuul:
  routes:
    core1:
      path: /products/**
      serviceId: core-app-1
      strip-prefix: false
    core2:
      path: /prices/**
      url: "${core-app-2-base-url}/prices"

logging:
  level:
    org.springframework.cloud.netflix.zuul: DEBUG
