core-app-1-url: http://localhost:9090
core-app-2-url: http://localhost:9091

zuul:
  routes:
    core1:
      path: /products/**
      url: "${core-app-1-url}/products"
    core2:
      path: /prices/**
      url: "${core-app-2-url}/prices"

